import 'package:flutter/material.dart';
import 'package:quote_app/pages/components/splash_login.dart';
import 'package:quote_app/pages/home.dart';
import 'package:quote_app/pages/loading.dart';
import 'package:quote_app/pages/choose_location.dart';

void main() {
  runApp(MaterialApp(initialRoute: '/home', routes: {
    '/': (context) => Loading(),
    '/home': (context) => Home(),
    '/splash_login_3_1': (context) => SplashLogin(),
    '/splash_login_4_2': (context) => SplashLogin(),
    '/splash_login_5_1': (context) => SplashLogin(),
    '/signup': (context) => ChooseLocation(),
    '/index': (context) => ChooseLocation(),
    '/card': (context) => ChooseLocation(),
    '/main_message_all': (context) => ChooseLocation(),
    '/graph_page': (context) => ChooseLocation(),
    '/google_link': (context) => ChooseLocation(),
    '/tenpo_menu': (context) => ChooseLocation(),
    '/tenpo_menu_list': (context) => ChooseLocation(),
    '/store_user_info_1_6': (context) => ChooseLocation(),
    '/tenpo_menu_coupon_9': (context) => ChooseLocation(),
    '/store_user_information_picture': (context) => ChooseLocation(),
    '/coupon_detail_01': (context) => ChooseLocation(),
    '/coupon_usage_inquiry': (context) => ChooseLocation(),
    '/map': (context) => ChooseLocation(),
    '/mental_check': (context) => ChooseLocation(),
    '/quest_view_00': (context) => ChooseLocation(),
    '/quest_view_01': (context) => ChooseLocation(),
    '/main_record_1': (context) => ChooseLocation(),
    '/main_record_3': (context) => ChooseLocation(),
    '/main_record_4': (context) => ChooseLocation(),
    '/questioneare_02': (context) => ChooseLocation(),
    '/medical_check': (context) => ChooseLocation(),
    '/bank_branch_store_information': (context) => ChooseLocation(),
    '/record_walk': (context) => ChooseLocation(),
    '/special_coupon_1': (context) => ChooseLocation(),
    '/special_coupon_7': (context) => ChooseLocation(),
    '/stamp_seal': (context) => ChooseLocation(),
    '/benefits_note': (context) => ChooseLocation(),
    '/change_benefits': (context) => ChooseLocation(),
    '/confirm_benefits': (context) => ChooseLocation(),
    '/used_benefits': (context) => ChooseLocation(),
    '/local_tickets': (context) => ChooseLocation(),
    '/guide': (context) => ChooseLocation(),
    '/FAQ': (context) => ChooseLocation(),
    '/lp': (context) => ChooseLocation(),
    '/lp_web_event': (context) => ChooseLocation(),
    '/stamp_rally': (context) => ChooseLocation(),
    '/stress_check': (context) => ChooseLocation(),
    '/smoking_check': (context) => ChooseLocation(),
    '/kfg_men': (context) => ChooseLocation(),
  }));
}
